### ISSUE TITLE
Move RADIUSS home from top menu to catalog/lefthand menu

### ISSUE THREAD

**Issue by hauten** [LLNL/llnl.github.io#311]
PR #484 (`radiuss-move` branch)
- [x] Replace placeholder .svg icon
- [x] Create new repo category like in issue #258
- [x] Don't change categories in https://github.com/LLNL/llnl.github.io/tree/main/category (but store .svg in the same place)
- [x] Figure out how to make `description2` align with icon 
- [x] Add category to main catalog browse (/category/#/RADIUSS, category_info.json)
- [x] Make sure there are no conflicts with issues #244 and #280 (or modify those issues accordingly)

PR #509
- [x] Add link to P&G on RADIUSS index.html

PR #523
- [x] Figure out how to make "Radiuss" all caps on /category/#/RADIUSS left-hand menu

Long-term PRs
- [x] *Evaluate the tasks below in light of dev.llnl.gov issue 8* - edit 8/2/21: I'm thinking we put these enhancements on ice not only b/c of the new area of the dev.llnl.gov internal site, but also b/c of PR #514. I will, however, try to make the all-caps task (above) happen.
~~Make sure /radiuss tree structure is retained~~
~~Retain existing layout with categories exposed~~
~~Find a home in main menu for RADIUSS P&G page (or just link menu to /category/#/RADIUSS ?)~~
~~Update header (remove RADIUSS menu link)~~
~~Update RADIUSS About page with correct link to catalog~~
~~Check for RADIUSS links t/o repo and update as needed~~
~~Ask Adrien et al. to review/approve before merging the PR~~
~~After merge, ask Justin to update redirects from radiuss.llnl.gov and software.llnl.gov/radiuss to /category/#/RADIUSS~~

**Comment by hauten** [comment]
@IanLee1521 Do we still want to do this?

**Comment by IanLee1521** [comment]
@hauten yes I think this is still a good idea... The other thing we'll need to do is find a new home for the "Radiuss policies" page.

**Comment by hauten** [comment]
![radiuss move in progress](https://user-images.githubusercontent.com/31740953/101700579-234da900-3a32-11eb-8323-477ad796a4f9.PNG)
@IanLee1521 @LRWeber @adrienbernede - Please see this screen shot of this issue-in-progress. Thoughts/feedback?

**Comment by adrienbernede** [comment]
Title: maybe escape all the letters "\R\A\D\I\U\S\S"?
P&G: I think since this is currently our main achievement we should make it visible. "Check out the RADIUSS Policies & Guidelines here!"
Description: Can we reduce the text width?
Challenge: Do you mean displaying big categories? I think it would make sense indeed, also since all the projects are then appearing on the page (unlike with filter, where you need to know what you are looking for).

**Comment by hauten** [comment]
> Challenge: Do you mean displaying big categories? I think it would make sense indeed, also since all the projects are then appearing on the page (unlike with filter, where you need to know what you are looking for).

OK. I wanted to make sure this was a meaningful requirement before figuring out how to implement. I will try your other suggestions.

**Comment by hauten** [comment]
I edited the issue description above on 8/2/21 re; outstanding tasks in light of another PR in progress & work that's nearly complete on dev.llnl.gov.
